######################################################################
#
# File name : openmips_min_sopc_tb.udo
# Created on: Sun May 28 14:32:36 +0800 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
