# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modeltech_pe_10.5c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Computer Architecture/My-CPU/Final/Final.cache/wt} [current_project]
set_property parent.project_path {D:/Computer Architecture/My-CPU/Final/Final.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Computer Architecture/My-CPU/Final/Final.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/defines.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/id.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/mem_wb.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/regfile.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/div.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/mem.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/LLbit_reg.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/ctrl.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/cp0_reg.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/pc_reg.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/id_ex.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/hilo_reg.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/ex_mem.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/if_id.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/ex.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/inst_rom.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/openmips.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/data_ram.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/new/seg7x16.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/imports/Chapter11/openmips_min_sopc.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/new/clk_div.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/new/io_sel.v}
  {D:/Computer Architecture/My-CPU/Final/Final.srcs/sources_1/imports/sources_1/new/top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Computer Architecture/My-CPU/Final/Final.srcs/constrs_1/imports/new/top.xdc}}
set_property used_in_implementation false [get_files {{D:/Computer Architecture/My-CPU/Final/Final.srcs/constrs_1/imports/new/top.xdc}}]


synth_design -top top -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
